/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hacknife_lua_LuaNativeUtil */

#ifndef _Included_com_hacknife_lua_LuaNativeUtil
#define _Included_com_hacknife_lua_LuaNativeUtil

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hacknife_lua_LuaNativeUtil
 * Method:    createContext
 * Signature: ()Lcn/vimfung/luascriptcore/LuaContext;
 */
JNIEXPORT jobject JNICALL Java_com_hacknife_lua_LuaNativeUtil_createContext
  (JNIEnv *, jclass);

/*
 * Class:     com_hacknife_lua_LuaNativeUtil
 * Method:    addSearchPath
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_hacknife_lua_LuaNativeUtil_addSearchPath
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_hacknife_lua_LuaNativeUtil
 * Method:    setGlobal
 * Signature: (ILjava/lang/String;Lcn/vimfung/luascriptcore/LuaValue;)V
 */
JNIEXPORT void JNICALL Java_com_hacknife_lua_LuaNativeUtil_setGlobal
        (JNIEnv *, jclass, jint, jstring, jobject);

/*
 * Class:     com_hacknife_lua_LuaNativeUtil
 * Method:    getGlobal
 * Signature: (ILjava/lang/String;)Lcn/vimfung/luascriptcore/LuaValue;
 */
JNIEXPORT jobject JNICALL Java_com_hacknife_lua_LuaNativeUtil_getGlobal
        (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_hacknife_lua_LuaNativeUtil
 * Method:    catchException
 * Signature: (Lcn/vimfung/luascriptcore/LuaContext;Z)V
 */
JNIEXPORT void JNICALL Java_com_hacknife_lua_LuaNativeUtil_catchException
        (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     com_hacknife_lua_LuaNativeUtil
 * Method:    evalScript
 * Signature: (ILjava/lang/String;)Lcn/vimfung/luascriptcore/LuaValue;
 */
JNIEXPORT jobject JNICALL Java_com_hacknife_lua_LuaNativeUtil_evalScript
  (JNIEnv *, jclass, jint, jstring, jobject);

/*
 * Class:     com_hacknife_lua_LuaNativeUtil
 * Method:    evalScriptFromFile
 * Signature: (ILjava/lang/String;)Lcn/vimfung/luascriptcore/LuaValue;
 */
JNIEXPORT jobject JNICALL Java_com_hacknife_lua_LuaNativeUtil_evalScriptFromFile
  (JNIEnv *, jclass, jint, jstring, jobject);

/*
 * Class:     com_hacknife_lua_LuaNativeUtil
 * Method:    callMethod
 * Signature: (ILjava/lang/String;[Lcn/vimfung/luascriptcore/LuaValue;)Lcn/vimfung/luascriptcore/LuaValue;
 */
JNIEXPORT jobject JNICALL Java_com_hacknife_lua_LuaNativeUtil_callMethod
  (JNIEnv *, jclass, jint, jstring, jobjectArray, jobject);

/*
 * Class:     com_hacknife_lua_LuaNativeUtil
 * Method:    registerMethod
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_hacknife_lua_LuaNativeUtil_registerMethod
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_hacknife_lua_LuaNativeUtil
 * Method:    releaseNativeObject
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_hacknife_lua_LuaNativeUtil_releaseNativeObject
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_hacknife_lua_LuaNativeUtil
 * Method:    invokeFunction
 * Signature: (Lcn/vimfung/luascriptcore/LuaContext;Lcn/vimfung/luascriptcore/LuaFunction;[Lcn/vimfung/luascriptcore/LuaValue;)Lcn/vimfung/luascriptcore/LuaValue;
 */
JNIEXPORT jobject JNICALL Java_com_hacknife_lua_LuaNativeUtil_invokeFunction
  (JNIEnv *, jclass, jobject, jobject, jobjectArray, jobject);

JNIEXPORT void JNICALL Java_com_hacknife_lua_LuaNativeUtil_retainValue
        (JNIEnv *, jclass, jobject, jobject);

JNIEXPORT void JNICALL Java_com_hacknife_lua_LuaNativeUtil_releaseValue
        (JNIEnv *, jclass, jobject, jobject);

JNIEXPORT jboolean JNICALL Java_com_hacknife_lua_LuaNativeUtil_registerType
        (JNIEnv *, jclass, jobject, jstring, jstring, jstring, jclass, jobjectArray, jobjectArray, jobjectArray);

JNIEXPORT void JNICALL Java_com_hacknife_lua_LuaNativeUtil_raiseException(JNIEnv *, jclass, jobject, jstring);

JNIEXPORT void JNICALL Java_com_hacknife_lua_LuaNativeUtil_runThread(JNIEnv *, jclass, jobject, jobject, jobjectArray, jobject);

JNIEXPORT jobject JNICALL Java_com_hacknife_lua_LuaNativeUtil_createScriptController(JNIEnv *, jclass);

JNIEXPORT void JNICALL Java_com_hacknife_lua_LuaNativeUtil_scriptControllerSetTimeout(JNIEnv *, jclass, jobject, jint);

JNIEXPORT void JNICALL Java_com_hacknife_lua_LuaNativeUtil_scriptControllerForceExit(JNIEnv *, jclass, jobject);

JNIEXPORT jobject JNICALL Java_com_hacknife_lua_LuaNativeUtil_luaValueSetObject(JNIEnv *, jclass, jobject, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
